### ISSUE TITLE
PhpdocScalarFixer fails when param named in wrong case

### ISSUE THREAD

**Issue by Strate** [FriendsOfPHP/PHP-CS-Fixer#1322]
```php
/**
 * @Param string
 */
```
PhpdocScalarFixer fails on above example, with
```
exception 'ErrorException' with message 'Undefined offset: 1' in /devel/src/github/Strate/PHP-CS-Fixer/Symfony/CS/Fixer/Symfony/PhpdocScalarFixer.php:104
Stack trace:
#0 /devel/src/github/Strate/PHP-CS-Fixer/Symfony/CS/Fixer/Symfony/PhpdocScalarFixer.php(104): {closure}(8, 'Undefined offse...', '/devel/src/gith...', 104, Array)
#1 /devel/src/github/Strate/PHP-CS-Fixer/Symfony/CS/Fixer/Symfony/PhpdocScalarFixer.php(83): Symfony\CS\Fixer\Symfony\PhpdocScalarFixer->fixScalars(Object(Symfony\CS\DocBlock\Line), 'param')
#2 /devel/src/github/Strate/PHP-CS-Fixer/Symfony/CS/Fixer.php(206): Symfony\CS\Fixer\Symfony\PhpdocScalarFixer->fix(Object(SplFileInfo), '<?php\nuse Logic...')
#3 /devel/src/github/Strate/PHP-CS-Fixer/Symfony/CS/Fixer.php(148): Symfony\CS\Fixer->fixFile(Object(SplFileInfo), Array, false, false, Object(Symfony\CS\FileCacheManager))
#4 /devel/src/github/Strate/PHP-CS-Fixer/Symfony/CS/Console/Command/FixCommand.php(371): Symfony\CS\Fixer->fix(Object(Symfony\CS\Config\Config), false, false)
#5 /devel/src/github/Strate/PHP-CS-Fixer/vendor/symfony/console/Command/Command.php(259): Symfony\CS\Console\Command\FixCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /devel/src/github/Strate/PHP-CS-Fixer/vendor/symfony/console/Application.php(878): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /devel/src/github/Strate/PHP-CS-Fixer/vendor/symfony/console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\CS\Console\Command\FixCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /devel/src/github/Strate/PHP-CS-Fixer/vendor/symfony/console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /devel/src/github/Strate/PHP-CS-Fixer/php-cs-fixer(44): Symfony\Component\Console\Application->run()
#10 {main}
```

I suggest to write a `PhpdocParamNameCaseFixer` and run it before `PhpdocScalarFixer`. I am ready to work on PR, but I should know how acceptable my suggestion is.

**Comment by GrahamCampbell** [comment]
That's intentional, because in php 5, `String` is a valid class name.

**Comment by GrahamCampbell** [comment]
>  suggest to write a PhpdocParamNameCaseFixer and run it before PhpdocScalarFixer. I am ready to work on PR, but I should know how acceptable my suggestion is.

:-1: We should just make our scalar fixer configurable, like we have for the phpunit fixers.

**Comment by GrahamCampbell** [comment]
We should have an option to match case insensitively.

**Comment by Strate** [comment]
> That's intentional, because in php 5, String is a valid class name.
Please note that error in tag name: `@Param` instead of `@param`

**Comment by GrahamCampbell** [comment]
Oh right, hmmm.

**Comment by GrahamCampbell** [comment]
We probably need a fixer marked as "risky" to fix all those cases then, including `@Return`.

**Comment by GrahamCampbell** [comment]
There's a list of all valid tags here: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.10/Symfony/CS/DocBlock/Tag.php#L26.

**Comment by Strate** [comment]
At least, `PhpdocScalarFixer` should not fails. I can just fix it.

**Comment by keradus** [comment]
Closing due to merge of #1327.
Thank you @Strate
