### ISSUE TITLE
Fixer fails with tokenizing basic aliased use statements

### ISSUE THREAD

**Issue by dereuromark** [FriendsOfPHP/PHP-CS-Fixer#1471]
Fixer fails with tokenizing basic aliased use statements:

```
array(3) {
  'type' =>
  int(1)
  'filepath' =>
  string(74) "src/Project/B/Discount/Persistence/Propel/AbstractDiscount.php"
  'message' =>
  string(2337) "exception 'UnexpectedValueException' with message 'Missing block end' in /data/shop/development/current/vendor/fabpot/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php:374
Stack trace:
#0 /data/shop/development/current/vendor/fabpot/php-cs-fixer/Symfony/CS/Tokenizer/Tokens.php(541): Symfony\CS\Tokenizer\Tokens->findBlockEnd(2, 47)
#1 /data/shop/development/current/vendor/fabpot/php-cs-fixer/Symfony/CS/Fixer/Symfony/RemoveLeadingSlashUseFixer.php(36): Symfony\CS\Tokenizer\Tokens->getImportUseIndexes()
#2 /data/sh"...
}

```

The code is
```
<?php
/**
 * (c)
 */

namespace Project\B\Discount\Persistence\Propel;

use Orm\B\Discount\Persistence\Base\Discount as BaseDiscount;

/**
 * ...
 */
abstract class AbstractDiscount extends BaseDiscount
{

}
```

**Comment by GrahamCampbell** [comment]
What version please?

**Comment by GrahamCampbell** [comment]
I can't replicate this.

**Comment by dereuromark** [comment]
```
"name": "fabpot/php-cs-fixer",
            "version": "v1.10.2",
            "source": {
                "type": "git",
                "url": "https://github.com/FriendsOfPHP/PHP-CS-Fixer.git",
                "reference": "e8b3c4e41dc1484210fdc45363c41af6c2d56f20"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/FriendsOfPHP/PHP-CS-Fixer/zipball/e8b3c4e41dc1484210fdc45363c41af6c2d56f20",
                "reference": "e8b3c4e41dc1484210fdc45363c41af6c2d56f20",
                "shasum": ""
            }

**Comment by GrahamCampbell** [comment]
Is it still broken on the latest 1.11, or master?

**Comment by keradus** [comment]
```
D:\GIT\fork\PHP-CS-Fixer ((detached from v1.10.2))
λ php php-cs-fixer fix issue -vvv --dry-run --diff
F
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
   1) AbstractDiscount.php (no_empty_lines_after_phpdocs, phpdoc_short_description, no_blank_lines_after_class_opening)
      ---------- begin diff ----------
      --- Original
+++ New
@@ @@
 <?php
 /**
- * (c)
+ * (c).
  */
-

@@ @@
 {
-
 }


      ---------- end diff ----------

Fixing time per file:
[0.608 s] AbstractDiscount.php

Fixed all files in 0.616 seconds, 4.250 MB memory used
```

Perhaps, you use non-standard configuration (in .php_cs file or via command args)? if so - please share them

**Comment by GrahamCampbell** [comment]
That looks like the correct behaviour to me?

**Comment by GrahamCampbell** [comment]
@keradus Didn't recognise you there with the new profile pic. ;)

**Comment by keradus** [comment]
yes, my snippet shows that it works for me, I can't duplicate the exception

**Comment by keradus** [comment]
@GrahamCampbell you knwo, change the country, change the pic ! :P

**Comment by dereuromark** [comment]
Yes most likely another sniffer interferes.
It would be good if we could in some debug mode also validate the file integrity (valid PHP code) after a fixer is done.
Closing then for now until I can track down the exact source.

**Comment by GrahamCampbell** [comment]
> It would be good if we could in some debug mode also validate the file integrity (valid PHP code) after a fixer is done.

We do?

**Comment by keradus** [comment]
Yes, we do. But it may be turn off. Please see https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/1.11/Symfony/CS/Config/Config.php#L33
