### ISSUE TITLE
Test case that crashes php-cs-fixer

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1938]
Latest 2.x. Enable the fixers: `braces` and `elseif` only.

**Input:**

```php
<?php

	if ($foo) {
		//
	}
	else
/*-- TROLOLOL --*/
	if ($bar) {}
```

**Comment by keradus** [comment]
is it the same on 1.x as well ?

**Comment by GrahamCampbell** [comment]
D'no. Give me a few mins and I'll test and report back.

**Comment by GrahamCampbell** [comment]
The diff on 1.12.2 and 1.12.3 is identical, and is as follows:

```
      ---------- begin diff ----------
      --- Original
      +++ New
      @@ @@
       <?php

           if ($foo) {
               //
      +    } else {
      +        /*-- TROLOLOL --*/
      +    if ($bar) {
           }
      -    else
      -/*-- TROLOLOL --*/
      -    if ($bar) {}
      -
      +    }


      ---------- end diff ----------
```

The exception on the current master is:

```
RuntimeException: Index invalid or out of range in /root/PHP-CS-Fixer/src/Fixer/Basic/BracesFixer.php:479
Stack trace:
#0 /root/PHP-CS-Fixer/src/Fixer/Basic/BracesFixer.php(339): PhpCsFixer\Fixer\Basic\BracesFixer->findStatementEnd(Object(PhpCsFixer\Tokenizer\Tokens), 14)
#1 /root/PHP-CS-Fixer/src/Fixer/Basic/BracesFixer.php(41): PhpCsFixer\Fixer\Basic\BracesFixer->fixMissingControlBraces(Object(PhpCsFixer\Tokenizer\Tokens))
#2 /root/PHP-CS-Fixer/src/Runner/Runner.php(189): PhpCsFixer\Fixer\Basic\BracesFixer->fix(Object(Symfony\Component\Finder\SplFileInfo), Object(PhpCsFixer\Tokenizer\Tokens))
#3 /root/PHP-CS-Fixer/src/Runner/Runner.php(141): PhpCsFixer\Runner\Runner->fixFile(Object(Symfony\Component\Finder\SplFileInfo), Object(PhpCsFixer\Linter\LintingResult))
#4 /root/PHP-CS-Fixer/src/Console/Command/FixCommand.php(364): PhpCsFixer\Runner\Runner->fix()
#5 /root/PHP-CS-Fixer/vendor/symfony/console/Command/Command.php(256): PhpCsFixer\Console\Command\FixCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /root/PHP-CS-Fixer/vendor/symfony/console/Application.php(815): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /root/PHP-CS-Fixer/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(PhpCsFixer\Console\Command\FixCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /root/PHP-CS-Fixer/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /root/PHP-CS-Fixer/php-cs-fixer(45): Symfony\Component\Console\Application->run()
#10 {main}
```

**Comment by GrahamCampbell** [comment]
While 1.11.x is not throwing an exception, I'd still say the output is wrong.

**Comment by keradus** [comment]
I was able to reproduce exception on 1.11 as well
