### ISSUE TITLE
Another php-cs-fixer crash

### ISSUE THREAD

**Issue by GrahamCampbell** [FriendsOfPHP/PHP-CS-Fixer#1945]
Latest 2.x will crash with:

```
<?php

namespace Mockery\Fixtures;

class SemiReservedWordsAsMethods 
{
    function callable() {}
    function class() {}
    function trait() {}
    function extends() {}
    function implements() {}
    function static() {}
    function abstract() {}
    function final() {}
    function public() {}
    function protected() {}
    function private() {}
    function const() {}
    function enddeclare() {}
    function endfor() {}
    function endforeach() {}
    function endif() {}
    function endwhile() {}
    function and() {}
    function global() {}
    function goto() {}
    function instanceof() {}
    function insteadof() {}
    function interface() {}
    function namespace() {}
    function new() {}
    function or() {}
    function xor() {}
    function try() {}
    function use() {}
    function var() {}
    function exit() {}
    function list() {}
    function clone() {}
    function include() {}
    function include_once() {}
    function throw() {}
    function array() {}
    function print() {}
    function echo() {}
    function require() {}
    function require_once() {}
    function return() {}
    function else() {}
    function elseif() {}
    function default() {}
    function break() {}
    function continue() {}
    function switch() {}
    function yield() {}
    function function() {}
    function if() {}
    function endswitch() {}
    function finally() {}
    function for() {}
    function foreach() {}
    function declare() {}
    function case() {}
    function do() {}
    function while() {}
    function as() {}
    function catch() {}
    function die() {}
    function self() {}
    function parent() {}
}
```

Here is the exception:

```
RuntimeException: Index invalid or out of range in /root/PHP-CS-Fixer/src/Fixer/ControlStructure/NoUselessElseFixer.php:150
Stack trace:
#0 /root/PHP-CS-Fixer/src/Fixer/ControlStructure/NoUselessElseFixer.php(84): PhpCsFixer\Fixer\ControlStructure\NoUselessElseFixer->getPreviousBlock(Object(PhpCsFixer\Tokenizer\Tokens), 395)
#1 /root/PHP-CS-Fixer/src/Fixer/ControlStructure/NoUselessElseFixer.php(53): PhpCsFixer\Fixer\ControlStructure\NoUselessElseFixer->fixElse(Object(PhpCsFixer\Tokenizer\Tokens), 395)
#2 /root/PHP-CS-Fixer/src/Runner/Runner.php(189): PhpCsFixer\Fixer\ControlStructure\NoUselessElseFixer->fix(Object(Symfony\Component\Finder\SplFileInfo), Object(PhpCsFixer\Tokenizer\Tokens))
#3 /root/PHP-CS-Fixer/src/Runner/Runner.php(141): PhpCsFixer\Runner\Runner->fixFile(Object(Symfony\Component\Finder\SplFileInfo), Object(PhpCsFixer\Linter\LintingResult))
#4 /root/PHP-CS-Fixer/src/Console/Command/FixCommand.php(364): PhpCsFixer\Runner\Runner->fix()
#5 /root/PHP-CS-Fixer/vendor/symfony/console/Command/Command.php(256): PhpCsFixer\Console\Command\FixCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /root/PHP-CS-Fixer/vendor/symfony/console/Application.php(815): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /root/PHP-CS-Fixer/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(PhpCsFixer\Console\Command\FixCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /root/PHP-CS-Fixer/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /root/PHP-CS-Fixer/php-cs-fixer(45): Symfony\Component\Console\Application->run()
#10 {main}E
```

Source: https://github.com/padraic/mockery/blob/master/tests/Mockery/Fixtures/SemiReservedWordsAsMethods.php.

**Comment by SpacePossum** [comment]
and the linting went ok? This is online valid on PHP7 and if you fix it with another version of PHP the tokens seems off.

**Comment by GrahamCampbell** [comment]
> and the linting went ok? This is online valid on PHP7 and if you fix it with another version of PHP the tokens seems off.

Yes, I'm using PHP 7.0.7 to lint and fix the file.

**Comment by gharlan** [comment]
refs #1772 and #1837

**Comment by keradus** [comment]
Closing in favour of #1959, which is combining multiple threads of same issue (#1772, #1837, #1945).
Thank you @gharlan, @SpacePossum for discussion so far! Please, move forward discussion (if any) to new thread.
