### ISSUE TITLE
Symfony class not found when using .php_cs

### ISSUE THREAD

**Issue by Synchro** [FriendsOfPHP/PHP-CS-Fixer#2229]
I'm using php-cs-fixer from homebrew running with PHP 7. I have a `.php_cs` file like this:

```php
<?php

return Symfony\CS\Config::create()
    ->in(__DIR__)
    ->exclude('src/myproject/Models')
    ->level(Symfony\CS\FixerInterface::PSR2_LEVEL)
    ->setUsingCache(true)
;
```

but when I tell php-cs-fixer to use it with `php-cs-fixer fix --config-file=.php_cs --dry-run .`, I get this error:

```
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\CS\Config::in() in /Users/me/Sites/myproject/.php_cs:4
Stack trace:
#0 /usr/local/Cellar/php-cs-fixer/1.12.1/Symfony/CS/Console/Command/FixCommand.php(354): include()
#1 /usr/local/Cellar/php-cs-fixer/1.12.1/vendor/symfony/console/Command/Command.php(256): Symfony\CS\Console\Command\FixCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /usr/local/Cellar/php-cs-fixer/1.12.1/vendor/symfony/console/Application.php(818): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /usr/local/Cellar/php-cs-fixer/1.12.1/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\CS\Console\Command\FixCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /usr/local/Cellar/php-cs-f in /Users/me/Sites/myproject/.php_cs on line 4
```

It looks like dependencies are missing, or a vendor/autoload is not being run, but I see nothing in the docs relating to this. php-cs-fixer works fine if I don't use the config file.

**Comment by SpacePossum** [comment]
This is because you try to call `in()` on the configuration object and not on the `finder` the configuration uses to find the files it should fix. 

Try something like this:
```php
<?php

return Symfony\CS\Config::create()
    ->finder(
        Symfony\CS\Finder::create()
            ->in(__DIR__)
            ->exclude('src/myproject/Models')
    )
    ->level(Symfony\CS\FixerInterface::PSR2_LEVEL)
    ->setUsingCache(true)
;
```

**Comment by keradus** [comment]
just like that.

**Comment by keradus** [comment]
(btw, class **was** found, the method wasn't)

**Comment by Synchro** [comment]
Ah, thanks!
