### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function PhpCsFixer\utf8_decode()

### ISSUE THREAD

**Issue by kcloze** [FriendsOfPHP/PHP-CS-Fixer#2556]
- php: PHP 7.0.16-3+deb.sury.org~xenial+1 (cli) (built: Feb 22 2017 10:05:52) ( NTS )

- php-cs-fixer: 2.1.0

- command: /usr/local/bin/php-cs-fixer-v2 describe binary_operator_spaces

**get error msg:**
```
Description of binary_operator_spaces rule.
Binary operators should be surrounded by at least one space.

Fixer is configurable.
Aligns or unaligns `=` in consecutive assignments, or `=>` in array initializations
Default configuration: ['align_equals' => false, 'align_double_arrow' => false].

Fixing examples:
 * Example #1.
   ---------- begin diff ----------
   --- Original
   +++ New
   @@ @@
    <?php

   -$a   = 9000;
   +$a = 9000;
    $abc = 90001;

    $foo = array(
   -    "a"   => 9000,
   +    "a" => 9000,
        "abc" => 9001,
    );
   ----------- end diff -----------

 * Example #2. Fixing with configuration: ['align_equals' => false].
   ---------- begin diff ----------
   --- Original
   +++ New
   @@ @@
    <?php

   -$a   = 9000;
   +$a = 9000;
    $abc = 90001;
   ----------- end diff -----------


Fatal error: Uncaught Error: Call to undefined function PhpCsFixer\utf8_decode() in phar:///usr/local/bin/php-cs-fixer-v2/src/AbstractAlignFixerHelper.php:103
Stack trace:
#0 phar:///usr/local/bin/php-cs-fixer-v2/src/AbstractAlignFixerHelper.php(49): PhpCsFixer\AbstractAlignFixerHelper->replacePlaceholder(Object(PhpCsFixer\Tokenizer\Tokens))
#1 phar:///usr/local/bin/php-cs-fixer-v2/src/Fixer/Operator/BinaryOperatorSpacesFixer.php(253): PhpCsFixer\AbstractAlignFixerHelper->fix(Object(PhpCsFixer\StdinFileInfo), Object(PhpCsFixer\Tokenizer\Tokens))
#2 phar:///usr/local/bin/php-cs-fixer-v2/src/Fixer/Operator/BinaryOperatorSpacesFixer.php(100): PhpCsFixer\Fixer\Operator\BinaryOperatorSpacesFixer->runHelperFixers(Object(PhpCsFixer\StdinFileInfo), Object(PhpCsFixer\Tokenizer\Tokens))
#3 phar:///usr/local/bin/php-cs-fixer-v2/src/Console/Command/DescribeCommand.php(177): PhpCsFixer\Fixer\Operator\BinaryOperatorSpacesFixer->fix(Object(PhpCsFixer\StdinFileInfo), Object(PhpCsFixer\Tokenizer\Tokens))
#4 phar:///usr/local/bin/php-cs-fi in phar:///usr/local/bin/php-cs-fixer-v2/src/AbstractAlignFixerHelper.php on line 103
```

**Comment by SpacePossum** [comment]
Hi thanks for reporting!

PHP-CS-Fixer depends on the xml(-parser) extension through the [`utf8-decode`](http://php.net/manual/en/function.utf8-decode.php) function.

IMHO we should check if the extension is install during run-time and add it as dependency in `composer.json` (or refactor the dependency out). 

The extension is not part of the [Core extensions](http://php.net/manual/en/extensions.membership.php) (also not part of the bundled ones, but even than we should not assume it is always installed, however it is [is enabled by default](http://php.net/manual/en/xml.installation.php)).

For now you could either install and/or enable the extension (make sure to do it for cli) or disable the fixers that depend on this function.

**Comment by kcloze** [comment]
thanks, I fixed it by install php7.0-xml extenson.
but find another bug   #2472
