### ISSUE TITLE
Undefined class constant ‘PhpCsFixer\Fixer\PhpUnit\PhpUnitTargetVersion::VERSION_7_5’ 

### ISSUE THREAD

**Issue by mihailogajic** [FriendsOfPHP/PHP-CS-Fixer#4397]
#### The PHP version you are using (`$ php -v`):
=> 7.3.4
#### PHP CS Fixer version you are using (`$ php-cs-fixer -V`):
=> 2.14.2

#### The command you use to run PHP CS Fixer:
=> php-cs-fixer fix

The exception is: Fatal error: Uncaught Error: Undefined class constant ‘PhpCsFixer\Fixer\PhpUnit\PhpUnitTargetVersion::VERSION_7_5’ in phar:///home/build/.phive/phars/php-cs-fixer.phar/src/Console/ConfigurationResolver.php:726

**Comment by keradus** [comment]
we don't have `VERSION_7_5`.
show your configuration file

**Comment by zacksleo** [comment]
Got same issue here. I used brew install the tool. It seems that phpunit version in the mac does not compat with php-cs-fixer. Installed by composer fixed the issue.

**Comment by mihailogajic** [comment]
Actually I'm using phar file of php-cs-fixer delivered by phive. There this error occurs. Are you generating the phar file, or should turn to them? I guess @zacksleo got the same phar file.
Thanks!

**Comment by keradus** [comment]
Do you have a config file? If so, share it

**Comment by jbnv** [comment]
I'm now getting this exception in one of my projects where it was working fine before. 

PHP v7.1.21. Fixer v 2.12.2.

Configuration:
```
public function getConfiguration()
{
    $header = 'PHP CS Fixer configuration for TODO.';

    $finder = \PhpCsFixer\Finder::create();

    $config = \PhpCsFixer\Config::create()
        ->setRiskyAllowed(true)
        ->registerCustomFixers(new \NetShapers\Gears\Reflection\Fixers())
        ->setRules([
            'Gears/class_docblock' => true,
            'align_multiline_comment' => true,
            'array_indentation' => true,
            'array_syntax' => ['syntax' => 'short'],
            'blank_line_before_statement' => ['statements' => ['switch']],
            'blank_line_after_namespace' => true,
            'blank_line_after_opening_tag' => true,
            'backtick_to_shell_exec' => true,
            'binary_operator_spaces' => ['default' => 'single_space'],
            'braces' => [
                'allow_single_line_closure' => true,
                'position_after_anonymous_constructs' => 'same',
                'position_after_control_structures' => 'same',
                'position_after_functions_and_oop_constructs' => 'next',
            ],
            'cast_spaces' => ['space' => 'single'],
            'class_attributes_separation' => true,
            'class_definition' => true,
            'class_keyword_remove' => false, // dangerous!
            'combine_consecutive_issets' => true,
            'combine_consecutive_unsets' => true,
            'comment_to_phpdoc' => true,
            'compact_nullable_typehint' => true,
            'concat_space' => ['spacing' => 'none'],
            'date_time_immutable' => true,
            'declare_equal_normalize' => ['space' => 'single'],
            'dir_constant' => true,
            'elseif' => false,
            'ereg_to_preg' => true,
            'escape_implicit_backslashes' => true,
            'explicit_string_variable' => true,
            'final_internal_class' => true,
            'fully_qualified_strict_types' => true,
            'function_declaration' => ['closure_function_spacing' => 'one'],
            'function_to_constant' => ['functions' => ['get_class', 'get_called_class', 'php_sapi_name', 'phpversion', 'pi']],
            //'header_comment' => ['header' => $header],
            'heredoc_to_nowdoc' => true,
            'include' => true,
            'increment_style' => ['style' => 'pre'],
            'indentation_type' => true,
            'is_null' => false,
            'line_ending' => true,
            'linebreak_after_opening_tag' => true,
            'logical_operators' => false, // using and/or with lower precedence may be intentional
            'lowercase_cast' => true,
            'lowercase_constants' => true,
            'lowercase_keywords' => true,
            'lowercase_static_reference' => true,
            'magic_constant_casing' => true,
            'method_argument_space' => [
                'keep_multiple_spaces_after_comma' => false,
                'on_multiline' => 'ensure_fully_multiline',
            ],
            'method_chaining_indentation' => true,
            'modernize_types_casting' => true,
            'multiline_comment_opening_closing' => true,
            'native_constant_invocation' => true,
            'native_function_casing' => true,
            'native_function_invocation' => true,
            'no_alternative_syntax' => true,
            'new_with_braces' => true,
            'no_binary_string' => true,
            'no_blank_lines_after_class_opening' => false,
            'no_blank_lines_after_phpdoc' => true,
            'no_closing_tag' => true,
            'no_empty_comment' => true,
            'no_empty_phpdoc' => true,
            'no_empty_statement' => true,
            'no_extra_blank_lines' => ['tokens' => ['break', 'continue', 'extra', 'return', 'throw', 'use', 'parenthesis_brace_block', 'square_brace_block', 'curly_brace_block']],
            'no_leading_import_slash' => true,
            'no_leading_namespace_whitespace' => true,
            'no_mixed_echo_print' => ['use' => 'echo'],
            'no_multiline_whitespace_around_double_arrow' => true,
            'no_null_property_initialization' => true,
            'no_singleline_whitespace_before_semicolons' => true,
            'no_spaces_after_function_name' => true,
            'no_spaces_inside_parenthesis' => true,
            'no_superfluous_phpdoc_tags' => false, // we want all @param and @return tags
            'no_trailing_comma_in_list_call' => true,
            'no_trailing_comma_in_singleline_array' => true,
            'no_trailing_whitespace_in_comment' => true,
            'no_trailing_whitespace' => true,
            'no_unneeded_control_parentheses' => true,
            'no_unneeded_curly_braces' => true,
            'no_unneeded_final_method' => true,
            'no_unset_on_property' => false,
            'no_unused_imports' => true,
            'no_useless_else' => true,
            'no_useless_return' => true,
            'no_whitespace_before_comma_in_array' => true,
            'no_whitespace_in_blank_line' => true,
            'no_short_echo_tag' => true,
            'no_superfluous_elseif' => true,
            'no_unreachable_default_argument_value' => true,
            'normalize_index_brace' => true,
            'not_operator_with_space' => false,
            'not_operator_with_successor_space' => false,
            'object_operator_without_whitespace' => true,
            'ordered_class_elements' => ['order' => ['use_trait', 'constant_public', 'constant_protected', 'constant_private', 'property_public', 'property_protected', 'property_private', 'construct', 'destruct', 'magic', 'phpunit', 'method_public', 'method_protected', 'method_private'], 'sortAlgorithm' => 'alpha'],
            'ordered_imports' => ['sort_algorithm' => 'alpha'],

            'php_unit_construct' => ['assertions' => ['assertEquals', 'assertSame', 'assertNotEquals', 'assertNotSame']],
            'php_unit_fqcn_annotation' => true,
            'php_unit_internal_class' => true,
            'php_unit_ordered_covers' => true,
            'php_unit_no_expectation_annotation' => true,
            'php_unit_set_up_tear_down_visibility' => true,
            'php_unit_strict' => ['assertions' => ['assertAttributeEquals', 'assertAttributeNotEquals', 'assertEquals', 'assertNotEquals']],
            'php_unit_test_annotation' => ['case' => 'camel', 'style' => 'prefix'],
            'php_unit_test_case_static_method_calls' => ['call_type' => 'this'],
            'php_unit_test_class_requires_covers' => true,

            'phpdoc_add_missing_param_annotation' => true,
            'phpdoc_annotation_without_dot' => false,
            'phpdoc_align' => ['align' => 'left'],
            'php_unit_dedicate_assert' => ['target' => '5.6'],
            'phpdoc_indent' => true,
            'phpdoc_no_alias_tag' => ['replacements' => ['type' => 'var', 'link' => 'see']],
            'phpdoc_no_access' => true,
            'phpdoc_no_empty_return' => false,
            'phpdoc_no_package' => true,
            'phpdoc_order' => true,
            'phpdoc_return_self_reference' => ['replacements' => ['this' => 'self', '@this' => 'self', '$self' => 'self', '@self' => 'self']],
            'phpdoc_scalar' => ['types' => ['double', 'real']],
            'phpdoc_summary' => true,
            'phpdoc_to_comment' => true,
            'phpdoc_trim_consecutive_blank_line_separation' => true,
            'phpdoc_trim' => true,
            'phpdoc_types_order' => true,
            'phpdoc_types' => true,
            'phpdoc_var_without_name' => true,

            'pow_to_exponentiation' => true,
            'psr4' => true,
            'random_api_migration' => ['replacements' => ['getrandmax' => 'mt_getrandmax', 'rand' => 'mt_rand', 'srand' => 'mt_srand']],
            'return_assignment' => true,
            'self_accessor' => true,
            'semicolon_after_instruction' => true,
            'set_type_to_cast' => true,
            'short_scalar_cast' => true,
            'simplified_null_return' => true,
            'single_blank_line_at_eof' => true,
            'single_blank_line_before_namespace' => true,
            'single_class_element_per_statement' => true,
            'single_import_per_statement' => true,
            'single_line_after_imports' => true,
            'single_line_comment_style' => true,
            'standardize_increment' => true,
            'single_quote' => true,
            'space_after_semicolon' => true,
            'standardize_not_equals' => true,
            'strict_comparison' => true,
            'strict_param' => true,
            'string_line_ending' => true,
            'switch_case_semicolon_to_colon' => true,
            'switch_case_semicolon_to_colon' => true,
            'switch_case_space' => true,
            'ternary_operator_spaces' => true,
            'ternary_operator_spaces' => true,
            'trailing_comma_in_multiline_array' => true,
            'trim_array_spaces' => true,
            'trim_array_spaces' => true,
            'unary_operator_spaces' => true,
            'visibility_required' => true,
            'whitespace_after_comma_in_array' => true,
            'yoda_style' => false,
        ])
        ->setFinder($finder)
;

    // special handling of fabbot.io service if it's using too old PHP CS Fixer version
    if (false !== \getenv('FABBOT_IO')) {
        try {
            \PhpCsFixer\FixerFactory::create()
                ->registerBuiltInFixers()
                ->registerCustomFixers($config->getCustomFixers())
                ->useRuleSet(new \PhpCsFixer\RuleSet($config->getRules()));
        } catch (\PhpCsFixer\ConfigurationException\InvalidConfigurationException $e) {
            $config->setRules([]);
        } catch (UnexpectedValueException $e) {
            $config->setRules([]);
        } catch (InvalidArgumentException $e) {
            $config->setRules([]);
        }
    }

    return $config;
}
```

**Comment by jbnv** [comment]
I just did a Composer update in a project where Fixer was working and now I'm getting the same error in that project as well. Same configuration as above. 

Here's my stack trace, FYI.

```
Loaded config default from "/redacted/./.php_cs".
Using cache file ".php_cs.cache".
PHP Fatal error:  Uncaught Error: Undefined class constant 'PhpCsFixer\Fixer\PhpUnit\PhpUnitTargetVersion::VERSION_7_5' in phar:///usr/local/bin/php-cs-fixer/src/Console/ConfigurationResolver.php:725
Stack trace:
#0 phar:///usr/local/bin/php-cs-fixer/src/Console/ConfigurationResolver.php(632): PhpCsFixer\Console\ConfigurationResolver->validateRules(Array)
#1 phar:///usr/local/bin/php-cs-fixer/src/Console/ConfigurationResolver.php(325): PhpCsFixer\Console\ConfigurationResolver->getRuleSet()
#2 phar:///usr/local/bin/php-cs-fixer/src/Console/Command/FixCommand.php(208): PhpCsFixer\Console\ConfigurationResolver->getFixers()
#3 phar:///usr/local/bin/php-cs-fixer/vendor/symfony/console/Command/Command.php(251): PhpCsFixer\Console\Command\FixCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///usr/local/bin/php-cs-fixer/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\Argv in phar:///usr/local/bin/php-cs-fixer/src/Console/ConfigurationResolver.php on line 725

Fatal error: Uncaught Error: Undefined class constant 'PhpCsFixer\Fixer\PhpUnit\PhpUnitTargetVersion::VERSION_7_5' in phar:///usr/local/bin/php-cs-fixer/src/Console/ConfigurationResolver.php:725
Stack trace:
#0 phar:///usr/local/bin/php-cs-fixer/src/Console/ConfigurationResolver.php(632): PhpCsFixer\Console\ConfigurationResolver->validateRules(Array)
#1 phar:///usr/local/bin/php-cs-fixer/src/Console/ConfigurationResolver.php(325): PhpCsFixer\Console\ConfigurationResolver->getRuleSet()
#2 phar:///usr/local/bin/php-cs-fixer/src/Console/Command/FixCommand.php(208): PhpCsFixer\Console\ConfigurationResolver->getFixers()
#3 phar:///usr/local/bin/php-cs-fixer/vendor/symfony/console/Command/Command.php(251): PhpCsFixer\Console\Command\FixCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///usr/local/bin/php-cs-fixer/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\Argv in phar:///usr/local/bin/php-cs-fixer/src/Console/ConfigurationResolver.php on line 725
```

**Comment by SpacePossum** [comment]
```
<?php
    $header = 'PHP CS Fixer configuration for TODO.';

    $finder = PhpCsFixer\Finder::create()
        ->exclude('tests/Fixtures')
        ->in(__DIR__)
        ->append([__DIR__.'/php-cs-fixer'])
    ;

    $config = \PhpCsFixer\Config::create()
        ->setRiskyAllowed(true)
        //->registerCustomFixers(new \NetShapers\Gears\Reflection\Fixers())
        ->setRules([
            //'Gears/class_docblock' => true,
            'align_multiline_comment' => true,
            'array_indentation' => true,
            'array_syntax' => ['syntax' => 'short'],
            'blank_line_before_statement' => ['statements' => ['switch']],
            'blank_line_after_namespace' => true,
            'blank_line_after_opening_tag' => true,
            'backtick_to_shell_exec' => true,
            'binary_operator_spaces' => ['default' => 'single_space'],
            'braces' => [
                'allow_single_line_closure' => true,
                'position_after_anonymous_constructs' => 'same',
                'position_after_control_structures' => 'same',
                'position_after_functions_and_oop_constructs' => 'next',
            ],
            'cast_spaces' => ['space' => 'single'],
            'class_attributes_separation' => true,
            'class_definition' => true,
            'class_keyword_remove' => false, // dangerous!
            'combine_consecutive_issets' => true,
            'combine_consecutive_unsets' => true,
            'comment_to_phpdoc' => true,
            'compact_nullable_typehint' => true,
            'concat_space' => ['spacing' => 'none'],
            'date_time_immutable' => true,
            'declare_equal_normalize' => ['space' => 'single'],
            'dir_constant' => true,
            'elseif' => false,
            'ereg_to_preg' => true,
            'escape_implicit_backslashes' => true,
            'explicit_string_variable' => true,
            'final_internal_class' => true,
            'fully_qualified_strict_types' => true,
            'function_declaration' => ['closure_function_spacing' => 'one'],
            'function_to_constant' => ['functions' => ['get_class', 'get_called_class', 'php_sapi_name', 'phpversion', 'pi']],
            //'header_comment' => ['header' => $header],
            'heredoc_to_nowdoc' => true,
            'include' => true,
            'increment_style' => ['style' => 'pre'],
            'indentation_type' => true,
            'is_null' => false,
            'line_ending' => true,
            'linebreak_after_opening_tag' => true,
            'logical_operators' => false, // using and/or with lower precedence may be intentional
            'lowercase_cast' => true,
            'lowercase_constants' => true,
            'lowercase_keywords' => true,
            'lowercase_static_reference' => true,
            'magic_constant_casing' => true,
            'method_argument_space' => [
                'keep_multiple_spaces_after_comma' => false,
                'on_multiline' => 'ensure_fully_multiline',
            ],
            'method_chaining_indentation' => true,
            'modernize_types_casting' => true,
            'multiline_comment_opening_closing' => true,
            'native_constant_invocation' => true,
            'native_function_casing' => true,
            'native_function_invocation' => true,
            'no_alternative_syntax' => true,
            'new_with_braces' => true,
            'no_binary_string' => true,
            'no_blank_lines_after_class_opening' => false,
            'no_blank_lines_after_phpdoc' => true,
            'no_closing_tag' => true,
            'no_empty_comment' => true,
            'no_empty_phpdoc' => true,
            'no_empty_statement' => true,
            'no_extra_blank_lines' => ['tokens' => ['break', 'continue', 'extra', 'return', 'throw', 'use', 'parenthesis_brace_block', 'square_brace_block', 'curly_brace_block']],
            'no_leading_import_slash' => true,
            'no_leading_namespace_whitespace' => true,
            'no_mixed_echo_print' => ['use' => 'echo'],
            'no_multiline_whitespace_around_double_arrow' => true,
            'no_null_property_initialization' => true,
            'no_singleline_whitespace_before_semicolons' => true,
            'no_spaces_after_function_name' => true,
            'no_spaces_inside_parenthesis' => true,
            'no_superfluous_phpdoc_tags' => false, // we want all @param and @return tags
            'no_trailing_comma_in_list_call' => true,
            'no_trailing_comma_in_singleline_array' => true,
            'no_trailing_whitespace_in_comment' => true,
            'no_trailing_whitespace' => true,
            'no_unneeded_control_parentheses' => true,
            'no_unneeded_curly_braces' => true,
            'no_unneeded_final_method' => true,
            'no_unset_on_property' => false,
            'no_unused_imports' => true,
            'no_useless_else' => true,
            'no_useless_return' => true,
            'no_whitespace_before_comma_in_array' => true,
            'no_whitespace_in_blank_line' => true,
            'no_short_echo_tag' => true,
            'no_superfluous_elseif' => true,
            'no_unreachable_default_argument_value' => true,
            'normalize_index_brace' => true,
            'not_operator_with_space' => false,
            'not_operator_with_successor_space' => false,
            'object_operator_without_whitespace' => true,
            'ordered_class_elements' => ['order' => ['use_trait', 'constant_public', 'constant_protected', 'constant_private', 'property_public', 'property_protected', 'property_private', 'construct', 'destruct', 'magic', 'phpunit', 'method_public', 'method_protected', 'method_private'], 'sortAlgorithm' => 'alpha'],
            'ordered_imports' => ['sort_algorithm' => 'alpha'],

            'php_unit_construct' => ['assertions' => ['assertEquals', 'assertSame', 'assertNotEquals', 'assertNotSame']],
            'php_unit_fqcn_annotation' => true,
            'php_unit_internal_class' => true,
            'php_unit_ordered_covers' => true,
            'php_unit_no_expectation_annotation' => true,
            'php_unit_set_up_tear_down_visibility' => true,
            'php_unit_strict' => ['assertions' => ['assertAttributeEquals', 'assertAttributeNotEquals', 'assertEquals', 'assertNotEquals']],
            'php_unit_test_annotation' => ['case' => 'camel', 'style' => 'prefix'],
            'php_unit_test_case_static_method_calls' => ['call_type' => 'this'],
            'php_unit_test_class_requires_covers' => true,

            'phpdoc_add_missing_param_annotation' => true,
            'phpdoc_annotation_without_dot' => false,
            'phpdoc_align' => ['align' => 'left'],
            'php_unit_dedicate_assert' => ['target' => '5.6'],
            'phpdoc_indent' => true,
            'phpdoc_no_alias_tag' => ['replacements' => ['type' => 'var', 'link' => 'see']],
            'phpdoc_no_access' => true,
            'phpdoc_no_empty_return' => false,
            'phpdoc_no_package' => true,
            'phpdoc_order' => true,
            'phpdoc_return_self_reference' => ['replacements' => ['this' => 'self', '@this' => 'self', '$self' => 'self', '@self' => 'self']],
            'phpdoc_scalar' => ['types' => ['double', 'real']],
            'phpdoc_summary' => true,
            'phpdoc_to_comment' => true,
            'phpdoc_trim_consecutive_blank_line_separation' => true,
            'phpdoc_trim' => true,
            'phpdoc_types_order' => true,
            'phpdoc_types' => true,
            'phpdoc_var_without_name' => true,

            'pow_to_exponentiation' => true,
            'psr4' => true,
            'random_api_migration' => ['replacements' => ['getrandmax' => 'mt_getrandmax', 'rand' => 'mt_rand', 'srand' => 'mt_srand']],
            'return_assignment' => true,
            'self_accessor' => true,
            'semicolon_after_instruction' => true,
            'set_type_to_cast' => true,
            'short_scalar_cast' => true,
            'simplified_null_return' => true,
            'single_blank_line_at_eof' => true,
            'single_blank_line_before_namespace' => true,
            'single_class_element_per_statement' => true,
            'single_import_per_statement' => true,
            'single_line_after_imports' => true,
            'single_line_comment_style' => true,
            'standardize_increment' => true,
            'single_quote' => true,
            'space_after_semicolon' => true,
            'standardize_not_equals' => true,
            'strict_comparison' => true,
            'strict_param' => true,
            'string_line_ending' => true,
            'switch_case_semicolon_to_colon' => true,
            'switch_case_semicolon_to_colon' => true,
            'switch_case_space' => true,
            'ternary_operator_spaces' => true,
            'ternary_operator_spaces' => true,
            'trailing_comma_in_multiline_array' => true,
            'trim_array_spaces' => true,
            'trim_array_spaces' => true,
            'unary_operator_spaces' => true,
            'visibility_required' => true,
            'whitespace_after_comma_in_array' => true,
            'yoda_style' => false,
        ])
        ->setFinder($finder)
;

    // special handling of fabbot.io service if it's using too old PHP CS Fixer version
    if (false !== \getenv('FABBOT_IO')) {
        try {
            \PhpCsFixer\FixerFactory::create()
                ->registerBuiltInFixers()
                ->registerCustomFixers($config->getCustomFixers())
                ->useRuleSet(new \PhpCsFixer\RuleSet($config->getRules()));
        } catch (\PhpCsFixer\ConfigurationException\InvalidConfigurationException $e) {
            $config->setRules([]);
        } catch (UnexpectedValueException $e) {
            $config->setRules([]);
        } catch (InvalidArgumentException $e) {
            $config->setRules([]);
        }
    }

    return $config;
```
I've removed the custom rules and used this config on this project with succes. @jbnv can you try removing the custom rules and see if that helps?

**Comment by SpacePossum** [comment]
Closing as we don't have a new leads to work on, my guess for now is the custom fixers might be confused. Happy to reopen if someone has the time to help us to help people with this issue.
