### ISSUE TITLE
Call to undefined method PhpCsFixer\Config::create() in .php_cs.dist:8 - under Symfony and phpStorm

### ISSUE THREAD

**Issue by sabat24** [FriendsOfPHP/PHP-CS-Fixer#5318]
## Support question

I use fixer (3.0.x-dev 7e343ed) in Symfony project using that file to run it under phpStorm: `php-cs-fixer-symfony.bat`
Lately I started to get following error: 

```
Fatal error: Uncaught Error: Call to undefined method PhpCsFixer\Config::create() in .php_cs.dist:8
			Stack trace:
			#0 vendor\friendsofphp\php-cs-fixer\src\Console\ConfigurationResolver.php(936): include()
			#1 vendor\friendsofphp\php-cs-fixer\src\Console\ConfigurationResolver.php(229): PhpCsFixer\Console\ConfigurationResolver::separatedContextLessInclude('...')
			#2 vendor\friendsofphp\php-cs-fixer\src\Console\ConfigurationResolver.php(256): PhpCsFixer\Console\ConfigurationResolver->getConfig()
			#3 vendor\friendsofphp\php-cs-fixer\src\Console\Command\FixCommand.php(162): PhpCsFixer\Console\ConfigurationResolver->getConfigFile()
			#4 vendor\symfony\console\Command\Command.php(258): PhpCsFixer\Console\Command\FixCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

I upgraded Symfony from 4.4.x to 5.1.6, but I'm not sure if it's relevant. However I haven't changed anything else.

My .php_cs.dist file looks like presented below:

```
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__)
    ->exclude('var')
;

return PhpCsFixer\Config::create()
    ->setRules([
        '@Symfony' => true,
        'array_syntax' => ['syntax' => 'short'],
    ])
    ->setFinder($finder)
;
```

What should I change to get it work?

**Comment by sabat24** [comment]
Ehh, as always I found a solution after writing down the problem somewhere.

I didn't see that the `Config` class has changed. So it should be called in that way right now `return (new PhpCsFixer\Config())->setRules(...)`
