### ISSUE TITLE
Too few arguments to function PhpCsFixer\ConfigurationException\InvalidFixerConfigurationException

### ISSUE THREAD

**Issue by jtojnar** [FriendsOfPHP/PHP-CS-Fixer#5729]
## Bug report

When I try to migrate my code, it crashes:

```ShellSession
$ PHP_CS_FIXER_FUTURE_MODE=1 php-cs-fixer fix -vvv
PHP CS Fixer 2.19.0 Testament by Fabien Potencier and Dariusz Ruminski
Runtime: PHP 7.4.18
Loaded config default from "/home/jtojnar/Projects/guzzle-transcoder/.php-cs-fixer.php".
Using cache file ".php_cs.cache".

Fatal error: Uncaught ArgumentCountError: Too few arguments to function PhpCsFixer\ConfigurationException\InvalidFixerConfigurationException::__construct(), 1 passed in /home/jtojnar/Projects/guzzle-transcoder/vendor/friendsofphp/php-cs-fixer/src/Utils.php on line 197 and at least 2 expected in /home/jtojnar/Projects/guzzle-transcoder/vendor/friendsofphp/php-cs-fixer/src/ConfigurationException/InvalidFixerConfigurationException.php:37
Stack trace:
#0 /home/jtojnar/Projects/guzzle-transcoder/vendor/friendsofphp/php-cs-fixer/src/Utils.php(197): PhpCsFixer\ConfigurationException\InvalidFixerConfigurationException->__construct('To disable the ...')
#1 /home/jtojnar/Projects/guzzle-transcoder/vendor/friendsofphp/php-cs-fixer/src/RuleSet/RuleSet.php(57): PhpCsFixer\Utils::triggerDeprecation('To disable the ...', 'PhpCsFixer\\Conf...')
#2 /home/jtojnar/Projects/guzzle-transcoder/vendor/friendsofphp/php-cs-fixer/src/Console/ConfigurationResolver.php(671): PhpCsFixer\RuleSet\RuleSet->__construct(Array)
#3 /home/jtojnar/Projects/gu in /home/jtojnar/Projects/guzzle-transcoder/vendor/friendsofphp/php-cs-fixer/src/ConfigurationException/InvalidFixerConfigurationException.php on line 37
```

No error without future mode.

Looks like the `null` rule is the culprit:

```php
<?php

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__);

$rules = [
    'yoda_style' => null,
];

$config = new PhpCsFixer\Config();

return $config
    ->setRules($rules)
    ->setFinder($finder);
```

**Comment by julienfalque** [comment]
Should be fixed with #5730.

Note the command you executed is supposed to fail with the following message:
```
[yoda_style] To disable the rule, use "FALSE" instead of "NULL".
```
